import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { HeroUIProvider } from "@heroui/system";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.variable}>
        <HeroUIProvider>
          <main className="text-foreground bg-background">
            {children}
          </main>
        </HeroUIProvider>
      </body>
    </html>
  );
}
